# Generated by Django 5.0.4 on 2024-05-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cs2_news_app", "0002_alter_player_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="ranking",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
