# Generated by Django 5.0.4 on 2024-05-15 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cs2_news_app", "0003_alter_player_ranking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_name_big", models.CharField(max_length=255)),
                ("match_name_small", models.CharField(max_length=255)),
                ("score_1", models.IntegerField(default=0)),
                ("score_2", models.IntegerField(default=0)),
                ("time", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[("未开始", "未开始"), ("已结束", "已结束")], max_length=100
                    ),
                ),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "team1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="cs2_news_app.team",
                    ),
                ),
                (
                    "team2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="cs2_news_app.team",
                    ),
                ),
            ],
        ),
    ]
