# Generated by Django 3.2.9 on 2024-05-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs2_news_app', '0004_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
